architect:
  - l3r8yJ
secrets:
  settings.xml: l3r8yJ/home#assets/settings.xml
merge:
  script:
    - "mvn clean install -Pqulice --errors --batch-mode"
release:
  pre: false
  sensetive:
    - settings.xml
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pqulice-profile -Pqulice -Psonatype --errors --settings ../settings.xml